/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pkgConnector;

import java.awt.Component;
import static pkgConnector.MainFrame.AnalysisBar;
import static pkgConnector.MainFrame.mainSetCard;
import static pkgConnector.MainFrame.setCard;

/**
 *
 * @author pernice
 */
public class AnalysisSteps extends javax.swing.JPanel {

  //  private MainFrame.PanelsControl pippo;
    /**
     * Creates new form NewJPanel
     */
    public AnalysisSteps() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        PreProcButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        ModelSelButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        ClustResButton = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setLayout(new java.awt.GridBagLayout());

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new java.awt.GridBagLayout());

        jLabel4.setFont(new java.awt.Font("Dialog", 3, 36)); // NOI18N
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkgConnector/images/title.png"))); // NOI18N
        jLabel4.setToolTipText(null);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.PAGE_START;
        gridBagConstraints.insets = new java.awt.Insets(50, 10, 10, 10);
        jPanel4.add(jLabel4, gridBagConstraints);
        jLabel4.getAccessibleContext().setAccessibleName("Title");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setText("Pre Processing");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        jPanel1.add(jLabel2, gridBagConstraints);

        PreProcButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkgConnector/images/PreProcBig.png"))); // NOI18N
        PreProcButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PreProcButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(30, 30, 5, 30);
        jPanel1.add(PreProcButton, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        gridBagConstraints.weightx = 0.3;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 80, 0, 10);
        jPanel4.add(jPanel1, gridBagConstraints);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new java.awt.GridBagLayout());

        ModelSelButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkgConnector/images/ParamEstimBig.png"))); // NOI18N
        ModelSelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModelSelButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(30, 30, 5, 30);
        jPanel2.add(ModelSelButton, gridBagConstraints);

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel3.setText("Model Selection");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        jPanel2.add(jLabel3, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.PAGE_START;
        gridBagConstraints.weightx = 0.3;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 10);
        jPanel4.add(jPanel2, gridBagConstraints);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new java.awt.GridBagLayout());

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setText("Clustering Results");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        jPanel3.add(jLabel1, gridBagConstraints);

        ClustResButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkgConnector/images/ClustPlotBig.png"))); // NOI18N
        ClustResButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClustResButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(30, 30, 5, 30);
        jPanel3.add(ClustResButton, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_END;
        gridBagConstraints.weightx = 0.3;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 80);
        jPanel4.add(jPanel3, gridBagConstraints);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkgConnector/images/logo.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.PAGE_END;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanel4.add(jLabel5, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        add(jPanel4, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void ModelSelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModelSelButtonActionPerformed
        javax.swing.JLabel arrow = new javax.swing.JLabel();
        arrow.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkgConnector/images/space.png"))); // NOI18N
        arrow.setToolTipText(null);
        arrow.setName("ArrowModSel");
        AnalysisBar.add(arrow);
        
        javax.swing.JButton B4=new  javax.swing.JButton("Model Selection Steps");
        B4.addActionListener(new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B4ActionPerformed(evt);
            }
        });
        
        B4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkgConnector/images/ParamEstim.png")));
        B4.setToolTipText("Steps necessary for the model selection.");
        B4.setBorder(null);
        B4.setFocusable(false);
        B4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        B4.setMaximumSize(new java.awt.Dimension(200, 55));
        B4.setMinimumSize(new java.awt.Dimension(200, 55));
        B4.setPreferredSize(new java.awt.Dimension(200, 55));
        
        B4.setName("ModelSelStepsB");
        MainFrame.AnalysisBar.add(B4);
        
        MainFrame.mainSetCard("horizontalCard");
        MainFrame.setCard("Empty");
        
        MainFrame.PanelsControl.showPanel("paramestimpanel");
        //MainFrame.refresh();
    }//GEN-LAST:event_ModelSelButtonActionPerformed

    private void PreProcButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PreProcButtonActionPerformed
        javax.swing.JLabel arrow = new javax.swing.JLabel();
        arrow.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkgConnector/images/space.png"))); // NOI18N
        arrow.setToolTipText(null);
        arrow.setName("ArrowPreProc");
        AnalysisBar.add(arrow);
        
        javax.swing.JButton B3=new  javax.swing.JButton("Pre Processing Steps");
        B3.addActionListener(new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B3ActionPerformed(evt);
            }
        });
        B3.setName("PreProcStepsB");
        B3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkgConnector/images/PreProc.png")));
        B3.setToolTipText("Steps necessary for the data pre processing.");
        B3.setBorder(null);
        B3.setFocusable(false);
        B3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        B3.setMaximumSize(new java.awt.Dimension(200, 55));
        B3.setMinimumSize(new java.awt.Dimension(200, 55));
        B3.setPreferredSize(new java.awt.Dimension(200, 55));



        MainFrame.AnalysisBar.add(B3);
        
        MainFrame.mainSetCard("horizontalCard");
        MainFrame.setCard("Empty");
        
        MainFrame.PanelsControl.showPanel("preprocpanel");
        //MainFrame.refresh();
    }//GEN-LAST:event_PreProcButtonActionPerformed

    private void ClustResButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClustResButtonActionPerformed
        javax.swing.JLabel arrow = new javax.swing.JLabel();
        arrow.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkgConnector/images/space.png"))); // NOI18N
        arrow.setToolTipText(null);
        arrow.setName("ArrowClust");
        AnalysisBar.add(arrow);
        
        javax.swing.JButton B5=new  javax.swing.JButton("Clustering Results");
        B5.addActionListener(new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B3ActionPerformed(evt);
            }
        });
        B5.setName("ClustResStepsB");
        MainFrame.AnalysisBar.add(B5);
        B5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkgConnector/images/ClustPlots.png")));
        B5.setToolTipText("Steps necessary for the clustering inspection.");
        B5.setBorder(null);
        B5.setFocusable(false);
        B5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        B5.setMaximumSize(new java.awt.Dimension(200, 55));
        B5.setMinimumSize(new java.awt.Dimension(200, 55));
        B5.setPreferredSize(new java.awt.Dimension(200, 55));
        
        MainFrame.mainSetCard("horizontalCard");
        MainFrame.setCard("Empty");
        
        MainFrame.PanelsControl.showPanel("clustestimpanel");
      
        //MainFrame.refresh();
    }//GEN-LAST:event_ClustResButtonActionPerformed
    
    private void B3ActionPerformed(java.awt.event.ActionEvent evt) {
        MainFrame.setCard("Empty");
  
       //MainFrame.refresh();
    }
    
    private void B4ActionPerformed(java.awt.event.ActionEvent evt) {
        MainFrame.setCard("Empty");
        
        MainFrame.PanelsControl.showPanel("paramestimpanel");
        
    }
    
    private void B5ActionPerformed(java.awt.event.ActionEvent evt) {
        MainFrame.setCard("Empty");
        
        MainFrame.PanelsControl.showPanel("clustestimpanel");

       //MainFrame.refresh();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    javax.swing.JButton ClustResButton;
    javax.swing.JButton ModelSelButton;
    javax.swing.JButton PreProcButton;
    javax.swing.JLabel jLabel1;
    javax.swing.JLabel jLabel2;
    javax.swing.JLabel jLabel3;
    javax.swing.JLabel jLabel4;
    javax.swing.JLabel jLabel5;
    javax.swing.JPanel jPanel1;
    javax.swing.JPanel jPanel2;
    javax.swing.JPanel jPanel3;
    javax.swing.JPanel jPanel4;
    // End of variables declaration//GEN-END:variables
}
